# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import re
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(410, 150))
        Dialog.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Satoshi Medium")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 100, 341, 35))
        font = QtGui.QFont()
        font.setFamily("Satoshi Medium")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 370, 80))
        font = QtGui.QFont()
        font.setFamily("Satoshi Medium")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))

    def setDialogDetails(self, Dialog, title="", text="", textColor="color: rgb(0, 85, 0)"):
        """
        Sets the window title, text, and text color for the dialog.

        dialog: the dialog instance.
        title: the title of the dialog window.
        text: the text displayed in the dialog.
        textColor: the color of the text displayed in the dialog.
        """

        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", title))
        self.label.setText(_translate("Dialog", text))
        self.label.setStyleSheet(hex_to_rgb(textColor))

def hex_to_rgb(color):
    if (is_valid_rgb_color(color)):
        return color 
    
    # Convert hex to rgb

    color = color.lstrip('#')

    # Convert the hex code to RGB values
    r, g, b = tuple(int(color[i:i+2], 16) for i in (0, 2, 4))

    return f"color: rgb({r}, {g}, {b})"

def is_valid_rgb_color(color_string):
    # Regular expression to match "color: rgb(r, g, b)" where r, g, and b are integers (0-255)
    pattern = r"^color:\s*rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$"
    match = re.match(pattern, color_string)
    
    if match: return True
    return False